### ISSUE TITLE
Project uses travis.yml, but doesn't use a status image.

### ISSUE THREAD

**Issue by shalecraig** [hardening-io/puppet-ssh-hardening#39]
Status images are very easy to add.

http://docs.travis-ci.com/user/status-images/

**Comment by rndmh3ro** [comment]
Added in this commit.
https://github.com/hardening-io/puppet-ssh-hardening/commit/990bc5b70e3793efa7043d6cac3d2efe9f53c659

**Comment by shalecraig** [comment]
Thanks!
